leboncoin/spark-ios

- core/Sources/Extension/PropertyWrapper/ScaledUIMetric.swift
- core/Sources/Extension/PropertyWrapper/ScaledUIMetricTests.swift
ScaledUIMetric is a property wrapper for UIKit. It scales values according to the current trait collection content size and behaves similar to the @`ScaledMetric`-property wrapper for SwiftUI.
> Property Wrapper: ScaledUIMetric.

- .github/workflows/build-and-test.yml
- core/Sources/Components/RadioButton/View/RadioButtionGroupViewTests.swift
This PR changes GitHub actions workflow a bit. When performing snapshot tests, the same branch is checked out in spark-ios-snapshots like the spark-iOS PR source branch. This makes it easier to modify snapshots and resolves conflicting changes.
If there is no branch with the same name found in spark-ios-snapshots, the behavior is not changed at all. Then, the main branch for spark-ios-snapshots is used. This is useful when there are no snapshot-test-changes in the current PR.
> [Core] Checkout similar branch in snapshots repository.

- core/Sources/Components/Chip/View/ChipUIView.swift
Removed the top & bottom touch area padding.
See the [PR](https://github.com/adevinta/spark-ios-snapshots/pull/19)
Before / After:
> [Component] Chip/UIKit: Removed touch area padding.

- core/Sources/Components/RadioButton/View/SwiftUI/RadioButtionGroupViewTests.swift
- core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonGroupView.swift
- core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonView.swift
- core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonViewTests.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIViewTests.swift
- spark/Demo/Classes/View/Components/RadioButton/RadioButtonGroup.swift
Added 
- left label alignment
- horizontal layout
- removed touch area padding
> [Component] RadioButton SwiftUI: Horizontal layout

- core/Sources/Components/RadioButton/View/UIKit/RadioButtonToggleUIView.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonToggleUIViewTests.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupViewTests.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
Removed "Halo"-Padding from RadioButton-UIView.
Please also check the [Snapshot tests PR](https://github.com/adevinta/spark-ios-snapshots/pull/21).
> [Component] RadioButton UIKit / Remove Halo Padding from component.

- core/Demo/Classes/CheckboxGroupUIView_Previews.swift
- core/Demo/Classes/CheckboxUIView_Previews.swift
- core/Sources/Common/Combine/Publisher/Publisher-Subscribe.swift
- core/Sources/Common/Combine/Publisher/Publisher-SubscribeTests.swift
- core/Sources/Common/Enum/Either.swift
- core/Sources/Common/Enum/EitherTests.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewActionTests.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewDelegate.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewTests.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIViewActionTests.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIViewDelegate.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIViewTests.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupView.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
- spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroupViewController.swift
- spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxViewController.swift
- The state change interactions of the checkbox and the checkbox group UIKit components have changed from bindings to the changed values being both sent to an optional delegate and to a publisher.
- In the checkbox the tap action function `actionTapped` has been made internally accessible for unit testing
- In the checkbox group the `checkboxes` have internally accessible via get for unit testing
- Unit tests have been added to test the tap action and calls to the delegates and publishers
> [Checkbox#180] Replaced binding with delegate and publisher in UIKit Checkboxes

- core/Sources/Components/Button/Properties/Internal/Colors/ButtonColors.swift
- core/Sources/Components/Button/Properties/Internal/Colors/ButtonColorsTests.swift
- core/Sources/Components/Button/Properties/Internal/CurrentColors/ButtonCurrentColors.swift
- core/Sources/Components/Button/Properties/Internal/CurrentColors/ButtonCurrentColorsTests.swift
- core/Sources/Components/Chip/Model/ChipStateColors.swift
- core/Sources/Components/Chip/Model/ChipStateColorsTests.swift
- core/Sources/Components/Switch/Model/Internal/Colors/SwitchColors.swift
- core/Sources/Components/Switch/Model/Internal/Colors/SwitchColorsTests.swift
- core/Sources/Components/Switch/Model/Internal/Colors/SwitchStatusColors.swift
- core/Sources/Components/Switch/Model/Internal/Colors/SwitchStatusColorsTests.swift
- core/Sources/Components/Tag/Model/Colors/TagColors.swift
- core/Sources/Components/Tag/Model/Colors/TagColorsTests.swift
- core/Sources/Components/Tag/Model/ContentColors/TagContentColors.swift
- core/Sources/Components/Tag/Model/ContentColors/TagContentColorsTests.swift
- core/Sources/Theming/Content/Colors/ColorTokenTests.swift
- core/Sources/Theming/Content/Colors/Colors.swift
In the PR, the use of the hash value to check for equality is removed. This was technically incorrect. Two objects which are equal must always have the same hash value, but two objects with the same hash value may not be equal.
See [Hashable](https://developer.apple.com/documentation/swift/hashable)
- [-] Code documentation on publics
- [-] Accessibility
- [-] Demo update
- [-] Wiki
> [Fix] Equals.

- core/Sources/Common/DisplayedText/ViewModel/DisplayedTextViewModel.swift
- core/Sources/Common/DisplayedText/ViewModel/DisplayedTextViewModelTests.swift
- core/Sources/Components/Button/Properties/Internal/CurrentColors/ButtonCurrentColors+ExtensionTests.swift
- core/Sources/Components/Button/Properties/Internal/CurrentColors/ButtonCurrentColors.swift
- core/Sources/Components/Button/Properties/Internal/CurrentColors/ButtonCurrentColorsTests.swift
- core/Sources/Components/Button/UseCase/GetCurrentColors/ButtonGetCurrentColorsUseCase.swift
- core/Sources/Components/Button/UseCase/GetCurrentColors/ButtonGetCurrentColorsUseCaseTests.swift
- core/Sources/Components/Button/View/UIKit/ButtonUIView.swift
- core/Sources/Components/Button/ViewModel/ButtonViewModel.swift
- core/Sources/Components/Button/ViewModel/ButtonViewModelTests.swift
- core/Sources/Theming/Content/Colors/Colors.swift
Actually, when consumer set an attributedText and user tap on the button, the text color changed so we lost the attributedText color.
The review removed this problem.
> [Button] Fix text color when attributedText is set

- core/Sources/Common/DataType/Updateable.swift
- core/Sources/Components/Tab/Enum/TabState.swift
- core/Sources/Components/Tab/Properties/TabUIItemContent.swift
- core/Sources/Components/Tab/UseCases/TabGetIntentColorUseCase.swift
- core/Sources/Components/Tab/UseCases/TabGetIntentColorUseCaseTests.swift
- core/Sources/Components/Tab/ViewModel/TabItemViewModel.swift
- core/Sources/Components/Tab/ViewModel/TabItemViewModelTests.swift
Tab item view model and test cases were added. We tried to consider while developing, when tab state or content is changed, other objects shouldn't be updated if It isn't needed
> [Tab] Added view model for tab item.

- core/Sources/Components/Button/View/UIKit/ButtonUIView.swift
Replaced leading  equalTo + trailing  equalTo by leading greaterThanOrEqual + centerX  equalTo
> [Button#276] Fix button layout when extended

- core/Sources/Components/Badge/Constants/BadgeConstants.swift
- core/Sources/Components/Badge/View/UIKit/BadgeUIView.swift
- core/Sources/Components/Badge/ViewModel/BadgeViewModel.swift
- spark/Demo/Classes/View/Components/Badge/Badge+UIPresentable.swift
- spark/Demo/Classes/View/Components/Badge/BadgeComponentView.swift
- spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxViewController.swift
- spark/Demo/Classes/View/Components/Chip/ChipComponent.swift
In the UI-Kit variation of the Badge, the height was not correct. I noticed this, when implementing the tab item.
- The height has been fixed
- The presentation in the demo has been adapted to the new style with the possibility of interactively changing attributes.
- Properties of the UI-Kit component had to made public as modifiers of the view.
- Reduced access of BadgeViewModel from public to internal.
Please also approve the [updated snapshots](https://github.com/adevinta/spark-ios-snapshots/pull/43):
> [Badge#1138] Fixed height of BadgeUIView. 

- core/Sources/Components/Badge/Constants/BadgeConstants.swift
- core/Sources/Components/Badge/Properties/Private/BadgeSizeDependentAttributes.swift
- core/Sources/Components/Badge/UseCase/BadgeGetSizeAttributesUseCase.swift
- core/Sources/Components/Badge/UseCase/BadgeGetSizeAttributesUseCaseTests.swift
- core/Sources/Components/Badge/View/SwiftUI/BadgeView.swift
- core/Sources/Components/Badge/View/UIKit/BadgeUIView.swift
- core/Sources/Components/Badge/ViewModel/BadgeViewModel.swift
- core/Sources/Components/Badge/ViewModel/BadgeViewModelTests.swift
With the fix for the badge height [(PR),](https://github.com/adevinta/spark-ios/pull/280) I missed that the badge can have two sizes.
This is fixed in this PR.
Additionally, autoscaling didn't appear to work correctly, in my opinion, because the width constraint of the badge was calculated on the text size. This calculation is not necessary, adding leading and trialing constraints to the label are sufficient.
The width constraint of the badge is now a minimum width. It should not be smaller than the height.
Please also review the [updated snapshots](https://github.com/adevinta/spark-ios-snapshots/pull/45).
> [Badge#1189] Corrected autoscaling and badge height depending on size.

- .github/workflows/build-and-test.yml
The archived results uploaded to the action of SparkCore and Spark both had the same name and, therefore, the artifacts produced during runtime are overwritten.
> [Build] Use distinct names for archived test results.

- core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift
- core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
The checkbox was missing a default accessibility identifier.
> [Checkbox#1271] Added default accessibility identifier.

- core/Sources/Components/Tab/View/UIKit/TabItemUIViewSnapshotTests.swift
- spark/Demo/Classes/View/Components/Tab/TabUIComponentView.swift
There was a bug in the demo, when removing a tab item.
> [Tab#336] Fix removing tab items in demo.

- core/Sources/Components/Button/ViewModel/ButtonViewModelTests.swift
- stencil/sourcery-template/SparkCoreAutoMockable.stencil
The goal of the PR is to simplify some part of our tests.
- The sourcery.yml is updated to add ResetGeneratedMock protocol
- Replace manual reset on mock to reset method on Button
> [Tests] Add reset method on Sourcery

- core/Sources/Components/Chip/Enum/ChipAlignment.swift
- core/Sources/Components/Chip/Model/ChipState.swift
- core/Sources/Components/Chip/Model/ChipStateColors.swift
- core/Sources/Components/Chip/Model/ChipStateTests.swift
- core/Sources/Components/Chip/UseCase/GetChipColorsUseCase.swift
- core/Sources/Components/Chip/UseCase/GetChipColorsUseCaseTests.swift
- core/Sources/Components/Chip/View/ChipUIView.swift
- core/Sources/Components/Chip/View/ChipUIViewTests.swift
- core/Sources/Components/Chip/View/ChipViewModel.swift
- core/Sources/Components/Chip/View/ChipViewModelTests.swift
- spark/Demo/Classes/View/Components/Chip/ChipComponent.swift
- spark/Demo/Classes/View/Components/Chip/ChipComponentUIView.swift
Added calculation of intrinsic content size.
If the width can't be calculated because a component doesn't support intrinsic content size, then UIView.noIntrinsicMetric will be returned as the width. The height is always defined.
Additionally:
- the view was changed to a control. 
- the position of the icon aligned with the text can be changed (leading/trailing).
-  The chip may be disabled
The new snapshots are in a [PR](https://github.com/adevinta/spark-ios-snapshots/pull/51).
- [/] Code documentation on publics
- [/] Accessibility
- [/] Dynamic sizes
- [/] Identifiers
- [/] Tests
- [/] Demo update
- [/] Wiki
> [Chip#307] Added intrinsic content size,  isEnabled state and trailing icon support.

- core/Sources/Components/Button/View/UIKit/ButtonUIView.swift
- core/Sources/Components/Button/ViewModel/ButtonViewModel.swift
- core/Sources/Components/Button/ViewModel/ButtonViewModelTests.swift
Depending on the component implementation, there may be a problem with the size of the button.
So, to fix this issue, we need to get the height value from viewModel directly on the view initialization
> [Fix] Button: set real height on setup

- core/Sources/Components/Button/ViewModel/ButtonViewModelTests.swift
- core/Unit-tests/Classes/Publisher/PublisherMock.swift
- core/Unit-tests/Classes/Publisher/XCTest+PublisherMock.swift
- Add parameters on XCT methods (function, file, line)
- Add missing method (XCTAssertPublisherSinkValueNil)
- Improve set of value on PublisherMock (we don't want set value if it's nil)
> [Tech] PublisherMock: add missing data and method

- core/Sources/Common/Combine/Global/Publisher-Subscribe.swift
- spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIView.swift
The default subscriptions of the view models were on DispachQueue.main, but it is better to have them on the RunLoop.main.
> [Fix#433] Subscribe on RunLoop.main.

- core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift
- core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
- core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
- core/Sources/Components/Switch/ViewModel/SwitchViewModelTests.swift
- spark/Demo/Classes/View/Components/Switch/UIKit/SwitchComponentUIViewController.swift
- UIKit: Fix the constraints bugs when user set many time the same iOn value
- SwiftUI: Fix the icon color when the switch is disabled
> [Fix-462] Fix constraints on UIKit & image color on SwiftUI

- core/Sources/Components/Tab/View/SwiftUI/TabItemView.swift
The pressed state of the tab was at times not reset properly after tapping back and forth amongst tabs quickly.
> [Tab#347] Fix irregular pressed state on SwiftUI-Tab.

- core/Unit-tests/TestCase/Component/Constants/ComponentSnapshotTestConstants.swift
- core/Unit-tests/TestCase/Component/Enum/ComponentSnapshotTestMode.swift
- core/Unit-tests/TestCase/Component/Helpers/ComponentSnapshotTestHelpers.swift
- core/Unit-tests/TestCase/Component/TestCase/SwiftUIComponentSnapshotTestCase.swift
- core/Unit-tests/TestCase/Component/TestCase/UIKitComponentSnapshotTestCase.swift
- core/Unit-tests/TestCase/Deprecated/ComponentSnapshotTestCase.swift
- Split the UIKit and SwiftUI code to two classes
- Move Constant into an another files
- Add Mode to manage light & dark snapshot
- Add new snapshot method (one for UIKit and one for SwiftUI) with modes and deprecate the old ones
> [Snapshot] Refactoring: Snapshot TestCase

- core/Sources/Common/Combine/Global/Publisher+SubscribeExtension.swift
- core/Sources/Common/Combine/Global/UIScheduler.swift
We have some troubles when we update a component in UIKit because we use RunLoop scheduler when the view receive an new UI information from the ViewModel.
The goal of this review is to replace the RunLoop to a new UIScheduler (used by Polaris)
> [Thread-507] Replace RunLoop to new UIScheduler

- core/Sources/Components/Tag/View/UIKit/TagUIView.swift
The height of this component for the UIKit version doesn't use @ScaledUIMetric annotation.
So, if the user uses the dynamic font, the components doesn't work.
I added this @ScaledUIMetric for the heigth property and I saw an another problem.
The text was cut off at the bottom.
To resolve this problem, I move the icon to an new stackview with top and bottom space. So now, the text height is equal to the height of the component
> [Component-518] Tag UIKit Height: Add scalability

- spark/Demo/Classes/View/Components/Tab/UIKit/TabComponentUIViewModel.swift
The UIKit tab demo crashed, because a system image is no longer available.
> [Demo#542] Remove missing system image in demo.

- core/Sources/Components/Badge/ViewModel/BadgeViewModel.swift
- core/Sources/Components/Badge/ViewModel/BadgeViewModelTests.swift
The font was not updated when a new theme was set in the view model.
This has been corrected.
> [Badge#544] Update font when theme updates.

- spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
In the demo, the space container was not working correctly because of the changes to the subscribe scheduler.
> [Demo#546] Subscribe to space component on run loop main.

- core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift
- core/Sources/Components/Tag/View/UIKit/TagUIViewSnapshotTests.swift
Add an **aspectRatio** on the circle to have a 1:1 circle.
> [Fix-548] Switch: Space position inside toggle

- spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
- spark/Demo/Classes/View/Components/Main/ComponentUIViewModel.swift
Many components should have a **.leading** alignment value for the integrationStackView on ComponentUIView.
But at least the ProgressBar must have a **.fill** alignment.
So I added a property on the ComponentUIView init with the **.leading** default value.
> [Fix-559] Demo: Open the alignment of the integration StackView

- core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
One developer on Polaris found this problem on the switch:
1. Init the switch with isOn to false (or true)
2. set directly the isOn to a different value true (or false)
-> the switch userInteraction is disabled.
**Why**:
The userInteraction is always set to false before update the space position inside the toggle and reset to the old value when the animation is finished. But if a new value is set before the completion of the previous animation, **the bug appears**.
**Solution**:
- get the current userInteraction from the viewModel and not from the UIView
> [Fix-563] Switch: UserInteraction bug

- core/Sources/Components/Tab/View/UIKit/TabUIViewSnapshotTests.swift
The system image eraser is no longer available.
The snapshots have been updated under: https://github.com/adevinta/spark-ios-snapshots/pull/69
> [Fix] Tab snapshots tests.

- core/Sources/Components/Chip/View/UIKit/ChipUIView.swift
- spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIView.swift
- spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIViewController.swift
- spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIViewModel.swift
If the user adds a button as an extra component, the interaction on that button can be enabled by changing the interaction enabled on the stack view.
> [Chip#577] Give user possibility to enable action on extra component.

- core/Sources/Common/UIKit/Extension/Animation/UIView+ExecuteExtension.swift
- core/Sources/Components/Button/View/UIKit/ButtonUIView.swift
- core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
- spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentItemsUIView.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIView.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIViewModel.swift
- spark/Demo/Classes/View/Components/Switch/UIKit/SwitchComponentUIView.swift
- spark/Demo/Classes/View/Components/Switch/UIKit/SwitchComponentUIViewModel.swift
- Create an extension for UIView to manage code with and without animation (same for transition animation)
- Add public property on Button to manage animation.
- Add setOn et setEnabled on the Switch to manage the. The associated variables (isOn and isEnabled) change update the UI without animation (like apple does on UIKit)
- Update demo app to manage this animation (or not)
> [Fix-580] Components: remove some animations

- core/Sources/Common/Control/PropertyState/ControlPropertyState.swift
- core/Sources/Common/Control/PropertyState/ControlPropertyStateTests.swift
- core/Sources/Common/Control/PropertyStates/ControlPropertyStates.swift
- core/Sources/Common/Control/PropertyStates/ControlPropertyStatesTests.swift
- core/Sources/Common/Control/State/ControlState.swift
- core/Sources/Common/Control/Status/ControlStatus.swift
- core/Sources/Common/Control/Status/ControlStatusTests.swift
- core/Sources/Common/Control/UIView/UIControlStateImageView.swift
- core/Sources/Common/Control/UIView/UIControlStateLabel.swift
This PR contains all needed class to manage the control status on a UILabel and UIImageView (and later on SwiftUI).
- **UIControlStateLabel & UIControlStateImageView** to display the correct text/image for the current state
- **ControlState**: contains all state for UIKit and SwiftUI
- **ControlStatus**: contains the all status properties on Control
- **ControlPropertyStates**: contains all properties states for a Control
- **ControlPropertyState**:  contains a dynamic value for a state
> [Refacto-557] Button: Add common Control management

- core/Sources/Components/Icon/View/UIKit/IconUIView.swift
- core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
- core/Sources/Components/Tag/View/UIKit/TagUIView.swift
- Replace layoutIfNeeded to updateConstraintsIfNeeded when the updated value is a constraints
- Move the layoutIfNeeded to the mandatory child view and not the parent
> [Fix] performance improvement by removing layoutIfNeeded

- .gitmodules
- core/Sources/Components/Rating/Cache/CGLayerCache.swift
- core/Sources/Components/Rating/Enum/StarFillMode.swift
- core/Sources/Components/Rating/Enum/StarFillModeUnitTests.swift
- core/Sources/Components/Rating/Graphics/ShapeLayer.swift
- core/Sources/Components/Rating/Graphics/Star.swift
- core/Sources/Components/Rating/Model/StarConfiguration.swift
- core/Sources/Components/Rating/View/UIKit/StarUIView.swift
- core/Sources/Components/Rating/View/UIKit/StarUIViewTests.swift
- spark/Demo/Classes/View/Components/ComponentsViewController.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentUIView.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentUIViewModel.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentViewController.swift
As a preparation for the rating view, a single configurable rating star is implemented.
This star wil be used for the RatingView and the RatingInputControl.
The star is configurable. The configuration possibles are added to the demo.
> [Rating#589] Single star view

- spark/Demo/Classes/Helper/AnyIsTrue.swift
- spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIViewModel.swift
- spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemView.swift
- spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIViewModel.swift
- spark/Demo/Classes/View/Components/Tab/UIKit/TabComponentUIViewModel.swift
The usage of the checkbox in the demo was flakey. Changes from the checkbox only toggled a boolean in the viewmodel.
Due to another issue with the checkbox, that the initial value is emitted immediately after init, the checkbox was toggled twice and therefore the correct state wasn't represented.
> [Demo-629] Fix value received from checkbox.

- core/Sources/Components/Chip/View/UIKit/ChipUIView.swift
- core/Sources/Components/Rating/AccessibilityIdentifier/RatingDisplayAccessibilityIdentifier.swift
- core/Sources/Components/Rating/Enum/RatingDisplaySize.swift
- core/Sources/Components/Rating/Enum/RatingIntent.swift
- core/Sources/Components/Rating/Enum/RatingStarsCount.swift
- core/Sources/Components/Rating/Model/RatingSizeAttributes.swift
- core/Sources/Components/Rating/TestHelpers/RatingDisplayConfigurationSnapshotTests.swift
- core/Sources/Components/Rating/TestHelpers/RatingDisplayScenarioSnapshotTests.swift
- core/Sources/Components/Rating/UseCases/RatingGetColorsUseCase.swift
- core/Sources/Components/Rating/UseCases/RatingSizeAttributesUseCase.swift
- core/Sources/Components/Rating/UseCases/RatingSizeAttributesUseCaseTests.swift
- core/Sources/Components/Rating/View/RatingDisplayViewModel.swift
- core/Sources/Components/Rating/View/RatingDisplayViewModelTests.swift
- core/Sources/Components/Rating/View/UIKit/RatingDisplayUIView.swift
- core/Sources/Components/Rating/View/UIKit/RatingDisplayUIViewSnapshotTests.swift
- core/Sources/Components/Rating/View/UIKit/StarUIView.swift
- core/Sources/Components/Rating/View/UIKit/StarUIViewTests.swift
- spark/Demo/Classes/Extension/NumberFormatter.swift
- spark/Demo/Classes/View/Components/ComponentsViewController.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/RatingDisplayComponentUIView.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/RatingDisplayComponentUIViewModel.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/RatingDisplayComponentViewController.swift
- spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentUIViewModel.swift
This is the uIKit version of the rating display.
There is only one intent, but nonetheless an enum was created in accordance with all other components.
The API is a little more flexible than the specs define. In the specs, the rating display with five stars can have two sizes, small and medium. A rating display with one star should have the size of the rating input. 
A user can configure this, but the API doesn't block the user of configuring a five star rating with size `input`.
Snapshots are available: please see the PR https://github.com/adevinta/spark-ios-snapshots/pull/73.
- [/] Code documentation on publics
- [/] Accessibility
- [/] Dynamic sizes
- [/] Identifiers
- [/] Tests
- [/] Demo update
> [Rating#591] Rating display UI View and View-Model

- core/Sources/Common/Control/SwiftUI/Control.swift
- core/Sources/Common/Control/SwiftUI/ControlStateImage.swift
- core/Sources/Common/Control/SwiftUI/ControlStateImageTests.swift
- core/Sources/Common/Control/SwiftUI/ControlStateText.swift
- core/Sources/Common/Control/SwiftUI/ControlStateTextTests.swift
- core/Sources/Common/Control/SwiftUI/ControlTests.swift
- core/Sources/Common/Control/UIView/UIControlStateLabel.swift
This PR contains all needed class to manage the control status on a Text and Image SwiftUI (normal, pressed, selected, disabled states).
> [Button-557] Add Control for SwiftUI

- core/Sources/Common/Combine/Publisher/PublishingBinding.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
- spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIView.swift
- spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIViewModel.swift
There was a workaround in SparkKit (Polaris) to be able to use a single radio button without having to use the binding.
This code is now being moved to SparkCore.
> [RadioButton#629] Move single radio button support from polaris to spark

- core/Sources/Components/Button/AccessibilityIdentifier/ButtonAccessibilityIdentifier.swift
- core/Sources/Components/Button/Enum/Public/Alignment/ButtonAlignmentDeprecated.swift
- core/Sources/Components/Button/Enum/Public/ButtonEvent.swift
- core/Sources/Components/Button/Properties/Internal/Content/ButtonContent.swift
- core/Sources/Components/Button/UseCase/GetContent/ButtonGetContentUseCase.swift
- core/Sources/Components/Button/UseCase/GetContent/ButtonGetContentUseCaseTests.swift
- core/Sources/Components/Button/UseCase/GetCurrentColors/ButtonGetCurrentColorsUseCase.swift
- core/Sources/Components/Button/UseCase/GetIsOnlyIcon/ButtonGetIsOnlyIconUseCase.swift
- core/Sources/Components/Button/UseCase/GetSizes/ButtonGetSizesUseCase.swift
- core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCase.swift
- core/Sources/Components/Button/View/Common/ButtonSutSnapshotTests.swift
- core/Sources/Components/Button/View/UIKit/Deprecated/ButtonUIViewDelegate.swift
- core/Sources/Components/Button/View/UIKit/Deprecated/ButtonUIViewDeprecated+ExtensionSnapshotTests.swift
- core/Sources/Components/Button/View/UIKit/Deprecated/ButtonUIViewDeprecated.swift
- core/Sources/Components/Button/View/UIKit/Deprecated/ButtonUIViewSnapshotTests.swift
- core/Sources/Components/Button/ViewModel/Deprecated/ButtonViewModelDeprecated.swift
- core/Sources/Components/Button/ViewModel/Deprecated/ButtonViewModelDeprecatedDependencies.swift
- core/Sources/Components/Button/ViewModel/Deprecated/ButtonViewModelDeprecatedTests.swift
- spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentItemsUIView.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIView.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIViewModel.swift
- spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentViewController.swift
Deprecate all classes (UIView, Enum, UseCases, ...) which will no longer be used in the new button (next PR)
> [Button-557] Refactoring: Deprecated current button

- core/Sources/Components/Tab/View/SwiftUI/TabView.swift
When dynamic sizes changed, the underline under all tabs was not drawn correctly.
> [Tab#717] Fix rescaling issue.

- core/Sources/Components/Chip/View/UIKit/ChipUIView.swift
- spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIView.swift
Avoid the icon tint color being changed by the system.
> [Chip#736] Set tint adjustment mode on icon.

- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
- while we were creating viewmodel in CheckboxUIView we wouldn't pass intent parameter in it. It was fixed
- If CheckboxUIView has no text,  label should be hidden. It was fixed
> [Checkbox#744] Fix intent initiliaze and empty text issue

- core/Sources/Components/Rating/Enum/RatingDisplaySize.swift
- core/Sources/Components/Rating/TestHelpers/RatingDisplayScenarioSnapshotTests.swift
- core/Sources/Components/Rating/UseCases/RatingSizeAttributesUseCase.swift
- core/Sources/Components/Rating/UseCases/RatingSizeAttributesUseCaseTests.swift
Added an extra size (24px) to the rating display.
Updated snapshots https://github.com/adevinta/spark-ios-snapshots/pull/84
> [RatingDisplay#731] Added size 24px.

- core/Sources/Components/Button/View/UIKit/Button/ButtonUIView.swift
- core/Sources/Components/Button/View/UIKit/Icon/IconButtonUIView.swift
- core/Sources/Components/Button/View/UIKit/Main/ButtonMainUIView.swift
To be sure to have a square icon button, the width constraint have been changed:
- greaterThanOrEqualTo the height of the view is used by the button
- equalTo the height of the view is used by the icon button
> [Button] Split width constraint

- core/Sources/Components/ProgressTracker/AccessibilityIdentifier/ProgressTrackerAccessibilityIdentifier.swift
- core/Sources/Components/ProgressTracker/AccessibilityIdentifier/ProgressTrackerAccessibilityIdentifierTests.swift
- core/Sources/Components/ProgressTracker/Enum/ProgressTrackerInteractionState.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCase.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCaseTests.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCase.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCaseTests.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCase.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCaseTests.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTrackColorUseCase.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTrackColorUseCaseTests.swift
- core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetVariantColorsUseCaseable.swift
- core/Sources/Components/ProgressTracker/View/ProgressTrackerIndicatorViewModel.swift
- core/Sources/Components/ProgressTracker/View/ProgressTrackerIndicatorViewModelTests.swift
- core/Sources/Components/ProgressTracker/View/ProgressTrackerTrackViewModel.swift
- core/Sources/Components/ProgressTracker/View/ProgressTrackerTrackViewModelTests.swift
- core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModel.swift
- core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModelTests.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerContinuousUITouchHandlerTests.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerDiscreteUITouchHandlerTests.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerIndependentUITouchHandlerTests.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerIndicatorUIControl.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerTrackUIView.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUITouchHandler.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUITouchHandlerCreationTests.swift
- core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUITouchHandlerTests.swift
- spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIView.swift
- spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewController.swift
- spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewModel.swift
Added use interaction to the progress tracker:
There are four types of user interaction:
- discrete (similar to the UIPage control). The use can only navigate to an adjacent step and not skip any step. Only one navigation step is allowed with one interaction
- continuous (similar to UIPage control). The user can only navigate to an adjacent step, but may drag and move to other steps with one interaction. All current pages will be published, i.e. multiple values may be published with this interaction type.
- independent (Not available in UIPage control). The user can tap on any step.
- none: no interaction possible
> [ProgressTracker#790] Add user interactions

- core/Sources/Components/Button/View/UIKit/Main/ButtonMainUIView.swift
Add a default tap gesture recognizer without any action to detect the action/publisher/target action even if the parent view has a gesture recognizer
Why ? UIControl action/publisher/target doesn't work if the parent contains a gesture recognizer.
Note: Native UIButton add the same default recognizer to manage this use case.
> [Button-821] Default gesture

- core/Sources/Components/Button/View/UIKit/Main/ButtonMainUIView.swift
Because there is no animation on the native UIKit button, we need to change the default isAnimated value to false on Spark
> [Button-807] UIKit: change default isAnimated value

- core/Sources/Components/TextLink/Enum/Public/TextLinkIntent.swift
- core/Sources/Components/TextLink/UseCase/GetColor/TextLinkGetColorUseCase.swift
- core/Sources/Components/TextLink/UseCase/GetColor/TextLinkGetColorUseCaseTests.swift
**Ticket description:**
We need to add the OnSurface intent for the textlink after the new UI/UX decision:
Adding a new intent to the TextLink called “OnSurface” to cover the request (iOS only)
Because there is no pressed color for the OnSurface, the color will be the same when the user will pressed the textlink (at least for the moment). It will be rechallenged in the futur
**Snapshot testing** PR is [here](https://github.com/adevinta/spark-ios-snapshots/pull/90)
> [TextLink-836] Add onSurface intent

- core/Sources/Common/UIKit/Extension/UIControl/UIControl-EnableTouches.swift
- core/Sources/Components/Button/View/UIKit/Main/ButtonMainUIView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
- core/Sources/Components/Chip/View/UIKit/ChipUIView.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupView.swift
- core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
- core/Sources/Components/Rating/View/UIKit/RatingInputUIView.swift
- core/Sources/Components/Tab/View/UIKit/TabItemUIView.swift
- core/Sources/Components/Tab/View/UIKit/TabUIView.swift
- core/Sources/Components/TextLink/View/UIKit/TextLinkUIView.swift
- spark/Demo/Classes/View/Components/Main/ComponentUIView.swift
Add a default tap gesture recognizer without any action to detect the action/publisher/target action even if the parent view has a gesture recognizer
Why ? UIControl action/publisher/target doesn't work if the parent contains a gesture recognizer.
Note: Native UIButton add the same default recognizer to manage this use case.
> [UIControl-822] Add default gesture

- core/Sources/Components/Tab/View/SwiftUI/TabApportionsSizeView.swift
- core/Sources/Components/Tab/View/SwiftUI/TabEqualSizeView.swift
A bug occures on the tabs height in swifuti when the tabs are inside a vstack
This should fix it
> [Tabs] Fixed tabs height for swiftui

- .gitignore
To install sourcery, we'll now have to 
- curl -L https://github.com/krzysztofzablocki/Sourcery/releases/download/$VERSION/sourcery-$VERSION.zip -o sourcery.zip
- unzip sourcery.zip -d sourcery-bin
- ./sourcery-bin/bin/sourcery
Current used version should be 2.1.7
> [Git] Updated .gitignore with sourcery-bin and sourcery.zip

- core/Sources/Components/Slider/Constant/SliderConstants.swift
Related snapshot PR https://github.com/adevinta/spark-ios-snapshots/pull/92
> [Slider#1977] Updated Slider handle size from 24x24 to 32x32

- core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift
- core/Sources/Components/Checkbox/Model/CheckboxGroupViewModel.swift
- core/Sources/Components/Checkbox/Model/CheckboxGroupViewModelTests.swift
- core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
- core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
- core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
- spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxGroupView.swift
- spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
- I tried to fix all accessibility issue. 
- I removed indexes from checkbox identifier for items which are in checkbox group. I dont know If we change checkbox identifier in checkbox group as adding index.
-  I marked checkbox group as an list type. this mean; when client click space that isn't accessible part on checkbox group, First; Voice over will read checkbox group label or hint if they exist. I didn't specify from component side but consumer might set.
- I also didn't give trait to single checkbox item. Lots of app specify checkbox type  giving a value property.  ex: 
accessibilityValue = "Checkbox checked" or "Checkbox unchecked".
> [Checkbox#876] Fix accessibility issues

- core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
When you put swiftui single checkbox in stack, It might extend It's content according to parent's frame. It was fixed
> [Checkbox#866] Fix extanding content issue in stack for single checkbox

- core/Sources/Components/Tab/View/SwiftUI/TabItemView.swift
- core/Sources/Components/Tab/View/SwiftUI/TabItemViewSnapshotTests.swift
- core/Sources/Components/Tab/View/SwiftUI/TabSingleItem.swift
- core/Sources/Components/Tab/View/SwiftUI/TabView.swift
- core/Sources/Components/Tab/View/UIKit/TabItemUIView.swift
- core/Sources/Components/Tab/View/UIKit/TabUIView.swift
- core/Sources/Components/Tab/ViewModel/TabItemViewModel.swift
- core/Sources/Components/Tab/ViewModel/TabItemViewModelTests.swift
- core/Sources/Components/Tab/ViewModel/TabViewModel.swift
- core/Sources/Components/Tab/ViewModel/TabViewModelTests.swift
The use of the EnvironmentalModifier `isEnabledChanged` has been replaced with the Environment variable `isEnabled` and this environment variable is set on the view model.
> [Tabs#899] Change handling of disabling tabs.

- core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerVerticalView.swift
- core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerView.swift
- spark/Demo/Classes/View/Components/ProgressTracker/SwiftUI/ProgressTrackerComponent.swift
Added fixes for:
- The labels contained within the container were not touchable.
- In the vertical mode, a long label did not wrap correctly.
Example of labels not rendered correctly.
After update:
> [ProgressTracker#906] Fix touch area and label sizing in vertical model.

- core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonGroupView.swift
There was a extra bottom padding for horizontal radio button group on swiftui side. I fixed it.
> [Radiobutton#918] Fix horizontal radiobutton group bottom padding

- core/Sources/Components/Rating/View/RatingDisplayViewModel.swift
- core/Sources/Components/Rating/View/SwiftUI/RatingInputView.swift
This is an example of avoiding the isEnabledModifier.
In this example. The RatingInputView creates the view model and updates the enables state of the view model when the body is build. This viewmodel is then passed to internal rating views.
> [RatingInput#897] Rating display update disabled

- core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
Ceckbox group doesnt update layout immediately after change label alignment 
Uploading 330708480-aad264de-5124-446a-a109-303b1fa6580e.mov…
> [CheckboxGroup#939] Fix layout update issue after change alignment

- core/Sources/Components/Button/View/SwiftUI/Internal/ButtonContainerView.swift
- core/Sources/Components/Button/View/SwiftUI/Public/Button/ButtonView.swift
- core/Sources/Components/Button/View/SwiftUI/Public/Icon/IconButtonView.swift
- spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift
This PR fix the tap area trouble on SwiftUI (related to this [ticket](https://github.com/adevinta/spark-ios/issues/909))
> [Button-909] SwiftUI: Fix tap area

- core/Sources/Common/SwiftUI/Extension/EdgeInsets/EdgeInsets+Extension.swift
- core/Sources/Components/Button/Properties/Internal/Spacings/ButtonSpacings+ExtensionTests.swift
- core/Sources/Components/Button/Properties/Internal/Spacings/ButtonSpacings.swift
- core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCase.swift
- core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCaseTests.swift
- core/Sources/Components/Button/View/SwiftUI/Public/Button/ButtonView.swift
- core/Sources/Components/Button/View/UIKit/Button/ButtonUIView.swift
The vertical spacing is now removed, the height of the text is equals to the height of the button (the text is always centered vertically).
Related to this [ticket](https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=60966156).
> [Button-909] UIKit: Remove vertical spacing

- core/Sources/Components/Button/View/SwiftUI/Internal/ButtonContainerView.swift
- core/Sources/Components/Button/View/SwiftUI/Public/Button/ButtonView.swift
When we remove animation on the entire button without specify an value, some animations on the parent view of the button are also removed.
The fix found is to remove the animation for the text and for the frame.
> [Button-972] Fix button animation

- core/Sources/Components/BottomSheet/SwiftUI/PresentationDetent-MaxHeight.swift
- core/Sources/Components/BottomSheet/SwiftUI/View-Height.swift
- spark/Demo/Classes/View/Components/BottomSheet/SwiftUI/BottomSheetPresentedView.swift
- spark/Demo/Classes/View/Components/BottomSheet/SwiftUI/BottomSheetPresentingView.swift
The width of the SwiftUI bottom sheet didn't use the full screen:
Before
After:
The error was caused by `.fixedSize(horizontal: true, vertical: true)` and. has been corrected.
An additional maxHeight detent was taken from the spark-ios-component-bottomsheet branch for possible use by the users. This cannot break anything since it is new.
The demo was updated to be able to reproduce the bug.
> [BottomSheet#1051] Fix width of bottom sheet.

- .github/workflows/generateDemoApp.yml
The goal of this PR is to generate the SparkDemo.app each day of the week (sunday -> thursday) at noon.
The artifact are available on the [Github actions page](https://github.com/adevinta/spark-ios/actions/workflows/generateDemoApp.yml).
> [Action] Add schedule action to generate the demo app
