leboncoin/spark-ios

.gitignore, .sourcery.yml, scripts/sourcery.sh, stencil/sourcery-template/DefaultAutoMockable.stencil
- Add generated file on .gitignore
- Add sourcery.yml
- Add sourcery stencil
=> Add sourcery on Core

.github/workflows/build-and-test.yml, .sourcery.yml, core/Sources/Theming/Content/Border/Border.swift, core/Sources/Theming/Content/Colors/Colors.swift, core/Sources/Theming/Content/Colors/ColorsGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Colors/Content/Base/ColorsBase.swift, core/Sources/Theming/Content/Colors/Content/Base/ColorsBaseGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Colors/Content/Feedback/ColorsFeedback.swift, core/Sources/Theming/Content/Colors/Content/Feedback/ColorsFeedbackGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Colors/Content/Primary/ColorsPrimary.swift, core/Sources/Theming/Content/Colors/Content/Primary/ColorsPrimaryGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Colors/Content/Secondary/ColorsSecondary.swift, core/Sources/Theming/Content/Colors/Content/Secondary/ColorsSecondaryGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Colors/Content/States/ColorsStates.swift, core/Sources/Theming/Content/Colors/Content/States/ColorsStatesGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Dims/Dims.swift, core/Sources/Theming/Content/Elevation/Shadow/Drop/ElevationDropShadows.swift, core/Sources/Theming/Content/Elevation/Shadow/ElevationShadow.swift, core/Sources/Theming/Content/Layout/Layout.swift, core/Sources/Theming/Content/Typography/Typography.swift, core/Sources/Theming/Theme/Theme.swift, fastlane/Fastfile, scripts/fastlane/generate-sourcery-files.sh, scripts/fastlane/generate-swiftgen.sh, stencil/sourcery-template/SparkCoreAutoMockable.stencil
Add default UIColor/Color/UIFont/Font on stencil
Rename stencil
Add default value on colors for mock
=> Add Automockable on Them - Add Mock on colors

core/Sources/Common/TextStyle/Enum/TextStyle.swift, core/Sources/Common/TextStyle/UseCase/GetTextStyleUseCase.swift, core/Sources/Common/TextStyle/UseCase/GetTextStyleUseCaseTests.swift, core/Sources/Theming/Content/Typography/TypographyDefault.swift, spark/Sources/Theming/Content/SparkTypography.swift
- Add TextStyle enum
- Add GetTextStyle UseCase
- Add UseCase on TypographyDefault
=> [Core] Add TextStyle

core/Sources/Common/SwiftUI/Extension/EdgeInsets/EdgeInsets+Extension.swift, core/Sources/Common/SwiftUI/Extension/EdgeInsets/EdgeInsets+ExtensionTests.swift, core/Sources/Common/UIKit/Extension/NSLayoutConstraint/NSLayoutConstraint+Extension.swift, core/Sources/Common/UIKit/Extension/UIEdgeInsets/UIEdgeInsets+Extension.swift, core/Sources/Common/UIKit/Extension/UIEdgeInsets/UIEdgeInsets+ExtensionsTests.swift, core/Sources/Common/UIKit/Extension/UIView/UIView+LayerExtension.swift
UIKit: 
- Add NSLayoutConstraint extension
- Add UIEdgeInsets extensions to simplify init
- Add UIView to manage layer
SwiftUI:
- Add EdgeInsets to simplify init
=> [Core] UIKit/SwiftUI: Add some extensions

SparkCore.yml, core/Unit-tests/Extension/UITraitCollection+ExtensionTests.swift, core/Unit-tests/SparkCoreTests.swift, core/Unit-tests/SparkCoreTestsUtils.swift, core/Unit-tests/TestCase/ComponentTestCase.swift, core/Unit-tests/TestCase/TestCase.swift, core/Unit-tests/TestCase/TestCaseTracker.swift
Automatically record snapshots for different dynamic type sizes.
=> [Core] Snapshot testing improvements.

core/Sources/Theming/Content/Dims/DimsGeneratedMock+ExtensionTests.swift, core/Sources/Theming/Content/Layout/LayoutGeneratedMock+ExtensionTests.swift
Copied mocks from Checkbox branch to have them available in other branches.
=> [Mocks] Copied mocks from Checkbox

core/Sources/Components/RadioButton/View/RadioButtionGroupViewTests.swift
Fix broken snapshot tests for RadioButton
=> [RadioButton] Fix snapshots on main.

core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
=> [Component] Fix checkbox horizontal layout.

core/Sources/Common/FullColorToken/FullColorToken.swift, core/Sources/Common/FullColorToken/FullColorTokenDefault+ExtensionTests.swift, core/Sources/Common/FullColorToken/FullColorTokenDefault.swift, core/Sources/Common/FullColorToken/FullColorTokenDefaultTests.swift, core/Sources/Components/Switch/Model/Internal/SwitchColors.swift, core/Sources/Components/Switch/UseCase/GetColors/SwitchGetColorsUseCase.swift, core/Sources/Components/Switch/UseCase/GetColors/SwitchGetColorsUseCaseTests.swift, core/Sources/Components/Switch/UseCase/GetToggleColor/SwitchGetToggleColorUseCase.swift, core/Sources/Components/Switch/UseCase/GetToggleColor/SwitchGetToggleColorUseCaseTests.swift, core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift, core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift, core/Sources/Components/Switch/ViewModel/SwitchViewModelTests.swift, core/Sources/Theming/Content/Colors/Colors.swift
- Replace all FullColorToken to ColorToken.
- Keep FullColorTokenDefault to init colorToken with opacity
=> [Code] Remove FullColorToken

core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCaseTests.swift, core/Sources/Components/Chip/Enum/ChipIntent.swift, core/Sources/Components/Chip/UseCase/GetChipColorsUseCase.swift, core/Sources/Components/Chip/UseCase/GetChipColorsUseCaseTests.swift, core/Sources/Components/Chip/UseCase/GetChipIntentColorsUseCase.swift, core/Sources/Components/Chip/View/ChipUIView.swift, core/Sources/Components/Chip/View/ChipUIViewTests.swift, core/Sources/Components/Chip/View/ChipViewModel.swift, core/Sources/Components/Chip/View/ChipViewModelTests.swift, core/Sources/Components/Spinner/SpinnerViewModelTests.swift, spark/Demo/Classes/Extension/CaseIterable-Name.swift, spark/Demo/Classes/View/Components/Chip/ChipComponent.swift, spark/Demo/Classes/View/Components/Chip/ChipComponentUIView.swift, spark/Demo/Classes/View/Components/ComponentsView.swift, spark/Demo/Classes/View/Components/Spinner/SpinnerComponent.swift
Changed the property "intentColor" to "intent" similar to recent changes on other components.
Changed the Demo to dynamically set attributes of the component. 
Dynamically changing these attributes uncovered some minor glitches that the view did not update correctly. These were corrected.
Some snapshots tests had to be recorded again. Please also review these changes under https://github.com/adevinta/spark-ios-snapshots/pull/38.
=> [Chip#227] Rename properties. Updated Demo.

core/Sources/Components/Tab/Enum/TabSize.swift, core/Sources/Components/Tab/Properties/TabStateAttributes.swift, core/Sources/Components/Tab/UseCases/TabGetFontUseCase.swift, core/Sources/Components/Tab/UseCases/TabGetFontUseCaseTests.swift, core/Sources/Components/Tab/UseCases/TabGetStateAttributesUseCase.swift, core/Sources/Components/Tab/UseCases/TabGetStateAttributesUseCaseTests.swift, core/Sources/Components/Tab/ViewModel/TabItemViewModel.swift, core/Sources/Components/Tab/ViewModel/TabItemViewModelTests.swift
The tabs support three different sizes. 
This use case calculates the size of the tab.
=> [Tab#286] Added use case for font.

core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
Fixing layout not updating before traitCollectionDidChange
=> [Switch#291] Fix layout issues

core/Sources/Common/DataType/Sequence-Compacted.swift, core/Sources/Components/Tab/AccessibilityIdentifier/TabItemAccessibilityIdentifier.swift, core/Sources/Components/Tab/Enum/TabSize.swift, core/Sources/Components/Tab/Properties/TabItemColors.swift, core/Sources/Components/Tab/Properties/TabItemHeights.swift, core/Sources/Components/Tab/Properties/TabState.swift, core/Sources/Components/Tab/Properties/TabStateAttributes.swift, core/Sources/Components/Tab/Properties/TabUIItemContent.swift, core/Sources/Components/Tab/UseCases/TabGetStateAttributesUseCase.swift, core/Sources/Components/Tab/UseCases/TabGetStateAttributesUseCaseTests.swift, core/Sources/Components/Tab/View/UIKit/TabItemUIView.swift, core/Sources/Components/Tab/View/UIKit/TabItemUIViewSnapshotTests.swift, core/Sources/Components/Tab/ViewModel/TabItemViewModel.swift, core/Sources/Components/Tab/ViewModel/TabItemViewModelTests.swift, spark/Demo/Classes/View/Components/Chip/ChipComponent.swift, spark/Demo/Classes/View/Components/Chip/ChipComponentUIView.swift, spark/Demo/Classes/View/Components/ComponentsView.swift, spark/Demo/Classes/View/Components/Tab/TabItemComponent.swift, spark/Demo/Classes/View/Components/Tab/TabItemUIComponentView.swift
A single tab item which may contain an icon, a text label and a badge.
The icon, label and badge are publicly accessible and their attributes may be changed by the user.
See [PR for snapshots](https://github.com/adevinta/spark-ios-snapshots/pull/46).
- [/] Code documentation on publics
- [/] Accessibility
- [/] Dynamic sizes
- [/] Identifiers
- [/] Tests
- [/] Demo update
=> [Component] Tab Item View 

core/Sources/Components/Badge/View/UIKit/BadgeUIView.swift, core/Sources/Components/Badge/View/UIKit/BadgeUIViewTests.swift
Calculate the intrinsic content size of the badge
=> [Badge#305] Calculate intrinsic content size.

core/Demo/Classes/BadgeUIView_Previews.swift, core/Demo/Classes/BadgeView_Previews.swift, core/Sources/Components/Badge/Constants/BadgeConstants.swift, core/Sources/Components/Badge/Properties/Public/BadgeSize.swift, core/Sources/Components/Badge/UseCase/BadgeGetSizeAttributesUseCase.swift, core/Sources/Components/Badge/UseCase/BadgeGetSizeAttributesUseCaseTests.swift, core/Sources/Components/Badge/View/SwiftUI/BadgeView.swift, core/Sources/Components/Badge/View/UIKit/BadgeUIView.swift, core/Sources/Components/Badge/ViewModel/BadgeViewModel.swift, core/Sources/Components/Badge/ViewModel/BadgeViewModelTests.swift, spark/Demo/Classes/View/Components/Badge/Badge+UIPresentable.swift, spark/Demo/Classes/View/Components/Badge/BadgeComponentView.swift
Please review the [snapshot PR](https://github.com/adevinta/spark-ios-snapshots/pull/50) too
=> [Badge#323] Update no count size

core/Sources/Components/Tab/View/UIKit/TabUIView.swift, core/Sources/Components/Tab/View/UIKit/TabUIViewTests.swift, spark/Demo/Classes/View/Components/Tab/TabUIComponentView.swift
=> [Tab#331] Fix scroll to issue and tab selection in demo.

spark/Demo/Classes/View/Components/Checkbox/ComponentsCheckboxListView.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroupViewController.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxViewController.swift, spark/Demo/Classes/View/Components/ComponentsView.swift, spark/Demo/Classes/View/Components/ComponentsViewController.swift
Checkbox was added to UIKit component list
=> [Tech#344] checkbox component

spark/Demo/Classes/View/Components/ComponentsViewController.swift, spark/Demo/Classes/View/Components/Main/ComponentUIView.swift, spark/Demo/Classes/View/Components/Switch/UIKit/SwitchComponentUIViewModel.swift, spark/Demo/Classes/View/Components/Tag/TagComponentItemsRepresentable.swift, spark/Demo/Classes/View/Components/Tag/TagComponentView.swift, spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIView.swift, spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIViewController.swift, spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIViewModel.swift
Tag component was added to UIKit list.
=> [Tech#406] tag component

core/Sources/Components/RadioButton/View/RadioButtonViewModel.swift, core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonView.swift, core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
THe problem was, that the label on the radio button was updated asynchronously. This caused problems when the radio button is used in a table view. The new cell height was not calculated correctly during the main runloop and the view had sizing problems.
=> [Radiobutton#402] Update label on radio button

spark/Demo/Classes/View/Components/Checkbox/ComponentsCheckboxListView.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroupViewController.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxViewController.swift
Checkbox group screen frozen issue was fixed.
=> [Fix#411] Fix demo app checkbox group screen frozen issue

core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCase.swift, core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCaseTests.swift, core/Sources/Components/Checkbox/UseCase/IntentColors/CheckboxStateColorsUseCase.swift, core/Sources/Components/Checkbox/UseCase/IntentColors/CheckboxStateColorsUseCaseTests.swift, core/Sources/Components/Chip/UseCase/GetChipColorsUseCase.swift, core/Sources/Components/Chip/UseCase/GetChipColorsUseCaseTests.swift, core/Sources/Components/Chip/UseCase/GetChipIntentColorsUseCase.swift, core/Sources/Components/Chip/UseCase/GetChipIntentColorsUseCaseTests.swift, core/Sources/Components/Chip/View/ChipUIView.swift, spark/Demo/SceneDelegate.swift
Renamed intentColor in intent
Added "Get" action on "CheckboxGetStateColorsUseCaseable" (was CheckboxStateColorsUseCaseable)
Changed a var to a let (removed a warning)
=> [Tech#282] Removed occurences of intentColor

core/Sources/Components/Button/ViewModel/ButtonViewModelTests.swift
- Move all mock values into a Stub
- Add PublisherMock to test all @Published values.
This PR is the continuation of this [one](https://github.com/adevinta/spark-ios/pull/413)
=> [Tech] Button: Improve ViewModel test

core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift, core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift, core/Sources/Components/Switch/ViewModel/SwitchViewModelDependencies.swift, core/Sources/Components/Switch/ViewModel/SwitchViewModelTests.swift
- ViewModel: set new value only if the value is different from the old one
- Tests: refacto all test (move mocked values inside stub, add missing tests, ...)
=> [Tech-343] Switch: Update ViewModel & test

core/Sources/Common/DisplayedText/Enum/DisplayedTextType.swift, core/Sources/Common/DisplayedText/Enum/DisplayedTextTypeTests.swift, core/Sources/Common/DisplayedText/Model/DisplayedText+ExtensionTests.swift, core/Sources/Common/DisplayedText/Model/DisplayedText.swift, core/Sources/Common/DisplayedText/Model/DisplayedTextTests.swift, core/Sources/Common/DisplayedText/ViewModel/DisplayedTextViewModel.swift, core/Sources/Common/DisplayedText/ViewModel/DisplayedTextViewModelTests.swift
- Add DisplayedText object
- On ViewModel: Deprecate text and attributedText and add displayedText property
=> [Tech] Update DisplayedTextViewModel: Add a model, deprecate some var

spark/Demo/Classes/View/Components/Main/ComponentUIView.swift, spark/Demo/Classes/View/Components/Main/Configuration/SwiftUI/RangeSelector.swift, spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemUIType.swift, spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemView.swift, spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/NumberSelector.swift, spark/Demo/Classes/View/Components/Tab/UIKit/TabComponentUIViewModel.swift
Add stepper and conversion properties into RangeSelector and NumberSelector
=> [Demo] Improve RangeSelector

core/Sources/Components/Tag/View/UIKit/TagUIView.swift
If there is no icon, le iconStackView must be hidden and not the Image...
It's fix on this PR !
=> [Fix-561] Tag: remove left space

core/Sources/Components/RadioButton/AccessibilityIdentifier/RadioButtonAccessibilityIdentifier.swift, core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
=> [RadioButton]add accessibility identifier on Radio button text label

core/Sources/Common/Enum/Either/Type/ViewEither.swift, core/Sources/Components/Chip/View/CommonTests/ChipConfigurationSnapshotTests.swift, core/Sources/Components/Chip/View/CommonTests/ChipScenarioSnapshotTests.swift, core/Sources/Components/Chip/View/CommonTests/ChipStateSnapshotTests.swift, core/Sources/Components/Chip/View/SwiftUI/ChipViewSnapshotTests.swift, core/Sources/Components/Chip/View/UIKit/ChipUIViewSnapshotTests.swift
See the snapshots under https://github.com/adevinta/spark-ios-snapshots/pull/71
=> [Chip#576] Updated snapshots for chip.

core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift, spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxView.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIViewController.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIViewModel.swift
Snapshot test will be fixed different pr
=> [Checkbox#476] update single swiftui checkbox

core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift, core/Sources/Components/Switch/View/SwiftUI/SwitchViewSnapshotTests.swift, spark/Demo/Classes/View/Components/Switch/SwiftUI/SwitchComponentView.swift
Replace default values on the **init** to parameters values.
Remove some modifiers (intent, alignment and isEnabled)
=> [Switch-596] Improve init and remove some modifiers

core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift, core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupItemProtocol.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewDelegate.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxUIViewActionTests.swift, spark/Demo/Classes/View/Components/Badge/UIKit/BadgeComponentUIView.swift, spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxGroupView.swift, spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxView.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIView.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIViewModel.swift, spark/Demo/Classes/View/Components/Main/Configuration/UIKit/Item/ComponentsConfigurationItemView.swift
Swiftui checkbox group updated
=> [Checkbox#477] update swiftui checkbox group

core/Sources/Components/Tag/View/SwiftUI/TagView.swift, core/Sources/Components/Tag/View/SwiftUI/TagViewSnapshotTests.swift, spark/Demo/Classes/View/Components/Tag/SwiftUI/TagComponentView.swift
Replace default values on the init to parameters values.
Deprecate some modifiers (intent and variant)
=> [Tag-613] Improve init and remove some modifiers

core/Sources/Components/Rating/Enum/RatingIntent.swift, core/Sources/Components/Rating/Model/RatingColors.swift, core/Sources/Components/Rating/Model/RatingState.swift, core/Sources/Components/Rating/UseCases/RatingGetColorsUseCase.swift, core/Sources/Components/Rating/UseCases/RatingGetColorsUseCaseUnitTests.swift, spark/Demo/Classes/View/Components/Main/Configuration/SwiftUI/Checkbox.swift
A use case to calculate the colors of the ratings.
=> [Rating#590] Add use case to calculate color

spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift, spark/Demo/Classes/View/Components/Main/Configuration/SwiftUI/Checkbox.swift
Main branch wasnt complied because of state parameter which is for swiftui checkbox initializer. I changed it with new parameter (isEnabled)
=> [Checkbox#627] Fix state parameter.

core/Sources/Common/Control/PropertyStates/ControlPropertyStates.swift, core/Sources/Common/Control/PropertyStates/ControlPropertyStatesTests.swift, core/Sources/Common/Control/UIView/UIControlStateImageView.swift, core/Sources/Common/Control/UIView/UIControlStateLabel.swift, core/Sources/Components/Button/View/UIKit/ButtonUIView.swift, core/Sources/Components/Button/View/UIKit/ButtonUIViewDelegate.swift, core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift, spark/Demo/Classes/View/Components/Button/ButtonContent.swift, spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentItemsUIView.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIView.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIViewModel.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentViewController.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonControlType.swift
=> Revert "Merge pull request #633 from adevinta/revert/button/integration"

core/Sources/Components/ProgressBar/View/Common/ProgressBarConfigurationSnapshotTests.swift, core/Sources/Components/ProgressBar/View/Common/ProgressBarScenarioSnapshotTests.swift, core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarDoubleViewSnapshotTests.swift, core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarViewSnapshotTests.swift, core/Sources/Components/ProgressBar/View/UIKit/ProgressBarDoubleUIViewSnapshotTests.swift, core/Sources/Components/ProgressBar/View/UIKit/ProgressBarUIViewSnapshotTests.swift
Add snapshot testing for:
- UIKit
- SwiftUI
The snapshot testing PR is [here](https://github.com/adevinta/spark-ios-snapshots/pull/67/commits/a480310917bbf291a60e723a333bf4bba86e96d9)
=> [Component] ProgressBar: Add snapshot testing

core/Sources/Components/Slider/Constant/SliderConstants.swift, core/Sources/Components/Slider/Properties/Private/SliderColors.swift, core/Sources/Components/Slider/Properties/Private/SliderColorsTests.swift, core/Sources/Components/Slider/Properties/Private/SliderRadii.swift, core/Sources/Components/Slider/Properties/Public/SliderIntent.swift, core/Sources/Components/Slider/Properties/Public/SliderShape.swift, core/Sources/Components/Slider/UseCase/GetColors/SliderGetColorsUseCase.swift, core/Sources/Components/Slider/UseCase/GetColors/SliderGetColorsUseCaseTests.swift, core/Sources/Components/Slider/UseCase/GetCornerRadii/SliderGetCornerRadiiUseCase.swift, core/Sources/Components/Slider/UseCase/GetCornerRadii/SliderGetCornerRadiiUseCaseTests.swift
1. Added SliderColors + SliderGetColorsUseCase
2. Added SliderShapes + SliderGetCornerRadiiUseCase
3. Added SliderConstants
=> [Slider#204] Colors & shapes + use cases

core/Sources/Components/Tab/View/UIKit/TabUIView.swift
The accessibility identifier was missing on the Tab (UIKit)
=> [Tab#648] Fix accessibility identifier.

core/Sources/Components/Rating/Enum/StarDefaults.swift, core/Sources/Components/Rating/Model/StarConfiguration.swift, core/Sources/Components/Rating/View/SwiftUI/RatingDisplayView.swift, core/Sources/Components/Rating/View/SwiftUI/RatingDisplayViewSnapshotTests.swift, core/Sources/Components/Rating/View/SwiftUI/StarShape.swift, core/Sources/Components/Rating/View/SwiftUI/StarView.swift, core/Sources/Components/Rating/View/UIKit/StarUIView.swift, spark/Demo/Classes/View/Components/ComponentsView.swift, spark/Demo/Classes/View/Components/Rating/SwiftUI/RatingComponent.swift
=> [RatingDisplay#667] SwiftUI Rating Display 

core/Sources/Common/SwiftUI/View/DoAction.swift
This will be needed in other PRs. That's why I've extracted it from the RatingInput PR.
=> [Fix#691] Add helper to detect changes to environment.

core/Sources/Components/RadioButton/View/SwiftUI/RadioButtonView.swift
Use the environment variable "isEnabled" to disable the radio button
=> [RadioButton#690] Use disabled state.

core/Sources/Components/Chip/View/SwiftUI/ChipView.swift, spark/Demo/Classes/View/Components/Chip/SwiftUI/ChipComponentView.swift
Used the environment variable "isEnabled" to detect if the view is disabled.
=> [Chip#694] Use environment disabled.

core/Sources/Components/Chip/View/CommonTests/ChipScenarioSnapshotTests.swift, core/Sources/Components/Tag/View/Common/TagScenarioSnapshotTests.swift, core/Sources/Components/TextLink/AccessibilityIdentifier/TextLinkAccessibilityIdentifier.swift, core/Sources/Components/TextLink/Enum/Public/Alignment/TextLinkAlignment.swift, core/Sources/Components/TextLink/Enum/Public/Alignment/TextLinkAlignmentTests.swift, core/Sources/Components/TextLink/Enum/Public/TextLinkTypography.swift, core/Sources/Components/TextLink/Enum/Public/TextLinkVariant.swift, core/Sources/Components/TextLink/Properties/Internal/ImageSize/TextLinkImageSize.swift, core/Sources/Components/TextLink/Properties/Internal/ImageSize/TextLinkImageSizeMock+ExtensionTests.swift, core/Sources/Components/TextLink/Properties/Internal/Typographies/TextLinkTypographies.swift, core/Sources/Components/TextLink/Properties/Internal/Typographies/TextLinkTypographiesMock+ExtensionsTests.swift, core/Sources/Components/TextLink/UseCase/GetAttributedString/TextLinkGetAttributedStringUseCase.swift, core/Sources/Components/TextLink/UseCase/GetAttributedString/TextLinkGetAttributedStringUseCaseTests.swift, core/Sources/Components/TextLink/UseCase/GetImageSize/TextLinkGetImageSizeUseCase.swift, core/Sources/Components/TextLink/UseCase/GetImageSize/TextLinkGetImageSizeUseCaseTests.swift, core/Sources/Components/TextLink/UseCase/GetTypographies/TextLinkGetTypographiesUseCase.swift, core/Sources/Components/TextLink/UseCase/GetTypographies/TextLinkGetTypographiesUseCaseTests.swift, core/Sources/Components/TextLink/UseCase/GetUnderline/TextLinkGetUnderlineUseCase.swift, core/Sources/Components/TextLink/UseCase/GetUnderline/TextLinkGetUnderlineUseCaseTests.swift, core/Sources/Theming/Content/Typography/TypographyGeneratedMock+ExtensionTests.swift, core/Unit-tests/Either/ImageEither+ExtensionSnapshotTests.swift, stencil/sourcery-template/SparkCoreAutoMockable.stencil, stencil/sourcery-template/SparkCoreAutoPublisherTest.stencil, stencil/sourcery-template/SparkCoreAutoViewModelStub.stencil
**TextLink**:
- Add AccessibilityIdentifiers
- Add all needed enum
- Add all needed models
- Add all needed use cases
**Common**:
- Add mock ImageEither and remove all same occurrence in the code (chip and tag)
- Fix sourcery stencil for **any MyProtocol**
On the next PRs:
- ViewModel
- View + Demo
The snapshot testing are [here](https://github.com/adevinta/spark-ios-snapshots/pull/79).
=> [TextLink#522#524] Add context

core/Sources/Common/Foundation/Extension/CGRect-Location.swift, core/Sources/Common/Foundation/Extension/CGRectLocationTests.swift, core/Sources/Common/Foundation/Extension/UIView-Closest.swift, core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift, core/Sources/Components/Rating/View/RatingDisplayViewModel.swift, core/Sources/Components/Rating/View/SwiftUI/RatingInputView.swift, core/Sources/Components/Rating/View/SwiftUI/RatingInputViewSnapshotTests.swift, core/Sources/Components/Rating/View/SwiftUI/StarView.swift, spark/Demo/Classes/View/Components/ComponentsView.swift, spark/Demo/Classes/View/Components/Rating/SwiftUI/RatingInputComponent.swift
=> [RatingInput#672] Rating Input SwiftUI

spark/Demo/Classes/Extension/UIViewController+Present.swift, spark/Demo/Classes/View/Components/Badge/UIKit/BadgeComponentViewController.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentViewController.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/Checkbox/CheckboxComponentUIViewController.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIViewController.swift, spark/Demo/Classes/View/Components/Chip/UIKit/ChipComponentUIViewController.swift, spark/Demo/Classes/View/Components/Icon/UIKit/IconComponentUIViewController.swift, spark/Demo/Classes/View/Components/ProgressBar/Indeterminate/UIKit/ProgressBarIndeterminateComponentUIViewController.swift, spark/Demo/Classes/View/Components/ProgressBar/Single/UIKit/ProgressBarComponentUIViewController.swift, spark/Demo/Classes/View/Components/RadioButton/UIKit/RadioButtonComponentUIViewController.swift, spark/Demo/Classes/View/Components/Rating/UIKit/RatingDisplayComponentViewController.swift, spark/Demo/Classes/View/Components/Rating/UIKit/RatingInputComponentViewController.swift, spark/Demo/Classes/View/Components/Rating/UIKit/StarComponentViewController.swift, spark/Demo/Classes/View/Components/Spinner/UIKit/SpinnerComponentUIViewController.swift, spark/Demo/Classes/View/Components/Switch/UIKit/SwitchComponentUIViewController.swift, spark/Demo/Classes/View/Components/Tab/UIKit/TabComponentUIViewController.swift, spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIViewController.swift, spark/Demo/Classes/View/Components/TextField/UIKit/TextFieldComponentUIViewController.swift, spark/Demo/Classes/View/SettingsViewController.swift
We have a crash on iPad when we display an alert.
This is solved by adding:
```swift
if let popoverController = viewControllerToPresent.popoverPresentationController {
popoverController.sourceView = self.view
popoverController.sourceRect = self.view.bounds
popoverController.permittedArrowDirections = []
}
```
=> [Demo-748] Fix alertcontroller crash on iPad

spark/Demo/Classes/View/Components/ComponentsViewController.swift, spark/Demo/Classes/View/Components/TextLink/SwiftUI/TextLinkComponentView.swift, spark/Demo/Classes/View/Components/TextLink/UIKit/TextLinkComponentUIView.swift, spark/Demo/Classes/View/Components/TextLink/UIKit/TextLinkComponentUIViewModel.swift
On the demo app:
* Replace the default value for the intent to basic
* Show a right space only for the simple text (and not for a paragraphe) for UIKit
=> [TextLink#522#524] Fix demo

core/Sources/Components/ProgressTracker/Enum/ProgressTrackerIntent.swift, core/Sources/Components/ProgressTracker/Enum/ProgressTrackerSize.swift, core/Sources/Components/ProgressTracker/Enum/ProgressTrackerVariant.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerColors.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerOutlinedColors.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerState.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerTintedColors.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetVariantColorsUseCaseable.swift
=> [ProgressTracker#740] Add use cases

core/Sources/Common/Foundation/Extension/Optional+Extension.swift, core/Sources/Common/Foundation/Extension/Optional+ExtensionTests.swift, core/Sources/Common/UIKit/Accessibility/AccessibilityLabelManager.swift, core/Sources/Common/UIKit/Accessibility/AccessibilityLabelManagerTests.swift, core/Sources/Common/UIKit/Extension/UIView/UIView+AccessibilityExtension.swift, core/Sources/Components/Button/View/SwiftUI/Internal/ButtonContainerView.swift, core/Sources/Components/Button/View/UIKit/Button/ButtonUIView.swift, core/Sources/Components/Button/View/UIKit/Icon/IconButtonUIView.swift, core/Sources/Components/Button/View/UIKit/Main/ButtonMainUIView.swift, spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIView.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonComponentUIViewModel.swift, spark/Demo/Classes/View/Components/Button/UIKit/ButtonControlType.swift, spark/Demo/Classes/View/Components/IconButton/SwiftUI/IconButtonComponentView.swift, spark/Demo/Classes/View/Components/IconButton/UIKit/IconButtonComponentUIView.swift
Fix all bugs/problems found by the QA team:
- spaces in the demo for the SwiftUI
- Add the button on the accessibilityTraits
- Manage the accessibility label (default value and when a consumer set a value)
- Add the toggle action on control type on the demo app
=> [Button-557] Fixes after QA review

core/Sources/Components/ProgressTracker/Enum/ProgressTrackerOrientation.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerColors.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerContent.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerContentTests.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerSpacing.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetColorsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetOutlinedColorsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetSpacingsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetSpacingsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTintedColorsUseCaseTests.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTrackColorUseCase.swift, core/Sources/Components/ProgressTracker/UseCase/ProgressTrackerGetTrackColorUseCaseTests.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerIndicatorViewModel.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerIndicatorViewModelTests.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModel.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModelTests.swift
Added view models and some more use cases
=> [Component] Progress Tracker add view model

core/Sources/Components/Button/View/SwiftUI/Public/Button/ButtonView.swift, core/Sources/Components/Button/ViewModel/Button/ButtonSUIViewModel.swift, core/Sources/Components/Button/ViewModel/Button/ButtonSUIViewModelTests.swift, spark/Demo/Classes/View/Components/Button/SwiftUI/ButtonComponentView.swift
It is not possible to have a specific width or a full width (from the available space) with the button on SwiftUI.
This PR fix the problem.
=> [Button-793] Manage the width on SwiftUI

core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCase.swift, core/Sources/Components/Checkbox/UseCase/Colors/CheckboxColorsUseCaseTests.swift, core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupViewSnapshotTests.swift, core/Sources/Components/Checkbox/View/SwiftUI/CheckboxViewSnapshotTests.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIViewSnapshotTests.swift
(Error, Success, Alert, Info, Neutral) intent's icon color was changed from onMain to onError, onSuccess, onAlert, onInfo, onNeutral
=> [Checkbox#803] checked image color was fixed

core/Sources/Components/Checkbox/Enum/CheckboxSelectionState.swift, spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
@frozen tag will be added from code side for consumers to apply component selection states more easily.
=> [checkbox#808] Add frozen tag to checkbox selection state enum

core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift, core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift, core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
=> [CheckboxGroup]add identifier on checkbox group View for UITests

core/Sources/Components/TextLink/View/SwiftUI/TextLinkView.swift, core/Sources/Components/TextLink/View/UIKit/TextLinkUIView.swift, spark/Demo/Classes/View/Components/TextLink/UIKit/TextLinkComponentUIView.swift, spark/Demo/Classes/View/Components/TextLink/UIKit/TextLinkComponentUIViewModel.swift
The component is not detected as a button by voice over and the label of the accessibility is not the good one.
The PR fix this problem.
=> [Textlink#772] Manage accessibility

core/Sources/Common/UIKit/Extension/UIControl/UIControl-EnableTouches.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerIndicatorUIControl.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift
=> [ProgressTracker#824] Fix testing session bugs

core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerIndicatorUIControl.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift
Corrected accessibility labels and accessibility traits
=> [ProgressTracker#831] Added accessibility values + traits.

core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupView.swift
=> [RadioButtonUIView]add RadioButtonUIView missing identifier

core/Sources/Components/Button/View/UIKit/Button/ButtonUIView.swift, core/Sources/Components/Button/View/UIKit/Icon/IconButtonUIView.swift, core/Sources/Components/Button/View/UIKit/Main/ButtonMainUIView.swift
We need to add the intrinsicContentSize for the Button and IconButton to fix some width issue on Polaris
=> [Button-840] Add intrinsic content size

core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift, core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
We need add and remove the .notEnabled accessibilityTrait on the toggleView in the Switch component
=> [Switch-843] Add accessibilityTrait

core/Sources/Components/Switch/View/SwiftUI/SwitchView.swift
Add accessibilityRepresentation to manage the correctly the trait for iOS 16 and lower
=> [Switch-847] Bug AccessibilityTrait - SwiftUI

core/Sources/Components/Tag/View/Common/TagConfigurationSnapshotTests.swift, core/Sources/Components/Tag/View/Common/TagScenarioSnapshotTests.swift, core/Sources/Components/Tag/View/SwiftUI/TagView.swift, core/Sources/Components/Tag/View/SwiftUI/TagViewSnapshotTests.swift, core/Sources/Components/Tag/View/UIKit/TagUIView.swift, core/Sources/Components/Tag/View/UIKit/TagUIViewSnapshotTests.swift, core/Sources/Components/Tag/ViewModel/TagViewModel.swift, core/Sources/Components/Tag/ViewModel/TagViewModelTests.swift, core/Unit-tests/Either/AttributedStringEither+ExtensionSnapshotTests.swift, spark/Demo/Classes/View/Components/Tag/SwiftUI/TagComponentView.swift, spark/Demo/Classes/View/Components/Tag/SwiftUI/TagComponentViewModel.swift, spark/Demo/Classes/View/Components/Tag/TagContent.swift, spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIView.swift, spark/Demo/Classes/View/Components/Tag/UIKit/TagComponentUIViewModel.swift, spark/Demo/Classes/View/ListView/Cells/TagCell/TagCell.swift, spark/Demo/Classes/View/ListView/ListViewDatasource.swift
=> [Tag] Add AttributedText

core/Sources/Common/UIKit/Extension/UIControl/UIControl-EnableTouches.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModel.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerContinuousGestureHandlerTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerDiscreteGestureHandlerTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerGestureHandler.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerHorizontalView.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerIndependentGestureHandlerTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerIndicatorView.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerVerticalView.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerView.swift, spark/Demo/Classes/View/Components/ProgressTracker/SwiftUI/ProgressTrackerComponent.swift, spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIView.swift, spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewModel.swift
This only contains the touch handling.
Adding accessibility identifiers is part of the next ticket.
=> [Progress-Tracker#830] Add user interaction to swiftui progress tracker

core/Sources/Common/UIKit/GlobalExtension/NSLayoutConstraint/NSLayoutConstraint+Extension.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerContent.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerContentTests.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerAccessibilityUIControl.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift, spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewModel.swift
The UIKit progress tracker accessibility traits are updated to correspond with those of SwiftUI.
A container view was added around to the indicator and the label to group the accessibility of these views.
=> [ProgressTracker#890] Updated accessibility traits of Progress Tracker (UIKit) 

core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModel.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModelTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerView.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift
Update the handling of the disabled state.
=> [ProgressTracker#895] SwiftUI Progress Tracker update disabled state

core/Sources/Common/UIKit/Extension/UIControl/UIControl+Extensions.swift, core/Sources/Common/UIKit/GlobalExtension/NSLayoutConstraint/NSLayoutConstraint+Extension.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerContent.swift, core/Sources/Components/ProgressTracker/Model/ProgressTrackerContentTests.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModel.swift, core/Sources/Components/ProgressTracker/View/ProgressTrackerViewModelTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerAccessibilityTraitsViewModifier.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerContinuousGestureHandlerTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerDiscreteGestureHandlerTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerGestureHandler.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerHorizontalView.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerIndependentGestureHandlerTests.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerIndicatorView.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerVerticalView.swift, core/Sources/Components/ProgressTracker/View/SwiftUI/ProgressTrackerView.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerAccessibilityUIControl.swift, core/Sources/Components/ProgressTracker/View/UIKit/ProgressTrackerUIControl.swift, spark/Demo/Classes/View/Components/ProgressTracker/SwiftUI/ProgressTrackerComponent.swift, spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIView.swift, spark/Demo/Classes/View/Components/ProgressTracker/UIKit/ProgressTrackerComponentUIViewModel.swift
This PR is for the release.
It is composed of the following issues
```[tasklist]
```
=> SwiftUI Progress Tracker

core/Sources/Components/Chip/View/UIKit/ChipUIView.swift, core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIGroupView.swift, core/Sources/Components/RadioButton/View/UIKit/RadioButtonUIView.swift
I removed safe area from chip and radio button.
=> [RadiobuttonChip#1989] Remove safe area from radio button and chip components

core/Sources/Components/RadioButton/UseCases/RadioButtonGetColorsUseCase.swift, core/Sources/Components/RadioButton/UseCases/RadioButtonGetColorsUseCaseTests.swift
The unselected radio button had the wrong color for some intents.
=> [RadioButton#968] Fix color.

core/Sources/Components/Tab/View/UIKit/TabUIView.swift
Quick fix for Version 0.16.2 needed. The changes to accessibility broke something in LBCTestKit
=> [Tab] Fix accessibility issues.

.github/workflows/actions.yml, .github/workflows/buildDemo.yml
=> [IRP-1015] Add new action before SPM migration

.Demo/Classes/Enum/UIComponent.swift, .Demo/Classes/View/ComponentVersionViewController.swift, .Demo/Classes/View/Components/ComponentsViewController.swift, .Demo/Classes/View/ListView/Cells/SwitchButtonCell/SwitchButtonCell.swift, .Demo/Classes/View/ListView/Cells/SwitchButtonCell/SwitchButtonConfiguration.swift, .Demo/Classes/View/ListView/ListComponentsViewController.swift, .Demo/Classes/View/ListView/ListViewController.swift, .Demo/Classes/View/ListView/ListViewDatasource.swift
- Replace *SwitchButton* to **Switch**
- Replace *uikit* to **UIKit** and *swiftui* to **SwiftUI**
=> [Demo] Update Demo

.Demo/Classes/Enum/UIComponent.swift, .Demo/Classes/View/Components/ComponentsViewController.swift, .Demo/Classes/View/Components/TextEditor/UIKit/TextEditorComponentUIView.swift, .Demo/Classes/View/Components/TextEditor/UIKit/TextEditorComponentUIViewController.swift, .Demo/Classes/View/Components/TextEditor/UIKit/TextEditorComponentUIViewModel.swift, .Demo/Classes/View/Components/TextField/UIKit/TextFieldComponentUIView.swift, Package.swift, Sources/Core/Core.swift
This PR :
- Add the TextEditor in SparkCore
- Add the TextEditor in Demo
- Replace TextField repository to TextInput
=> [SPA-35-36] Add TextEditor for UIKit

.github/workflows/actions.yml, .github/workflows/buildDemo.yml, .github/workflows/generateDemoApp.yml
Change the Xcode version to 16.2 and the iOS simulator to iPhone 16 pro in iOS 18.0
=> [Action] Update xCode version
